-- 1. INSERT DE CATEGORÍAS
INSERT INTO categoria (nombre, descripcion, estado) VALUES
                                                        ('Conciertos', 'Eventos musicales en vivo de diversos géneros.', 1),
                                                        ('Teatro', 'Obras dramáticas, comedia, musicales y microteatro.', 1),
                                                        ('Deportes', 'Partidos de fútbol, baloncesto, tenis y maratones.', 1),
                                                        ('Cine', 'Estrenos, festivales de cine y proyecciones especiales.', 1),
                                                        ('Festivales', 'Grandes festivales al aire libre de música y cultura.', 1),
                                                        ('Conferencias', 'Charlas magistrales, congresos y seminarios corporativos.', 1),
                                                        ('Infantil', 'Espectáculos, shows de magia y obras para niños.', 1),
                                                        ('Exposiciones', 'Galerías de arte, museos y ferias tecnológicas.', 1),
                                                        ('Danza', 'Ballet clásico, danza contemporánea y folklore.', 1); -- ◄ PUNTO Y COMA

-- 2. INSERT DE USUARIOS
INSERT INTO usuario (nombre, apellido_paterno, apellido_materno, email, contrasena, rol, estado, fecha_creacion) VALUES
                                                                                                                     ('Juan', 'Pérez', 'Gómez', 'juan.perez@email.com', 'scrypt_hash_1', 'ADMIN', 1, '2026-01-10'),
                                                                                                                     ('María', 'López', 'Martínez', 'maria.lopez@email.com', 'scrypt_hash_2', 'CLIENTE', 1, '2026-01-12'),
                                                                                                                     ('Carlos', 'García', 'Rodríguez', 'carlos.garcia@email.com', 'scrypt_hash_3', 'CLIENTE', 1, '2026-01-15'),
                                                                                                                     ('Ana', 'Sánchez', 'Fernández', 'ana.sanchez@email.com', 'scrypt_hash_4', 'VENDEDOR', 1, '2026-01-20'); -- ◄ PUNTO Y COMA

-- 3. INSERT DE EVENTOS
INSERT INTO evento (id_categoria, titulo, descripcion, fecha_evento, hora, precio, lugar, aforo_total, aforo_disponible, imagen_url, estado, destacado) VALUES
                                                                                                                                                            (1, 'Rock Fest 2026', 'Concierto con las mejores bandas de rock locales.', '2026-07-15', '20:00:00', 150.00, 'Estadio Nacional', 40000, 39950, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 1),
                                                                                                                                                            (2, 'Hamlet: El Clásico', 'Una adaptación moderna del clásico de Shakespeare.', '2026-07-20', '19:30:00', 80.00, 'Teatro Municipal', 500, 480, '/imagenes/Conciertos/CuartetoDeNos-12Marzo.webp', 1, 1),
                                                                                                                                                            (3, 'Gran Maratón Ciudad', 'Carrera de 42k por las principales avenidas.', '2026-08-05', '06:00:00', 45.00, 'Parque Central', 5000, 4980, '/imagenes/Conciertos/Paulo Londra-29Agosto.webp', 1, 0),
                                                                                                                                                            (3, 'Cine Bajo las Estrellas', 'Proyección al aire libre de clásicos de culto.', '2026-07-10', '21:00:00', 25.00, 'Plaza de las Artes', 300, 290, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 0),
                                                                                                                                                            (4, 'Festival Electrónico Beat', '12 horas continuas del mejor EDM mundial.', '2026-09-12', '16:00:00', 220.00, 'Explanada Verde', 15000, 14900, '/imagenes/Conciertos/CuartetoDeNos-12Marzo.webp', 1, 1),
                                                                                                                                                            (4, 'Tech Summit 2026', 'Conferencia sobre IA, Blockchain y Desarrollo.', '2026-10-10', '09:00:00', 350.00, 'Centro de Convenciones', 1200, 1180, '/imagenes/Conciertos/Paulo Londra-29Agosto.webp', 1, 0),
                                                                                                                                                            (4, 'Noche de Monólogos', 'El mejor stand-up comedy de la temporada.', '2026-07-18', '22:00:00', 60.00, 'Comedy Club Centro', 150, 140, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 1),
                                                                                                                                                            (5, 'El Mago de Oz - Infantil', 'Obra musical mágica pensada para toda la familia.', '2026-07-25', '16:00:00', 40.00, 'Auditorio San Ángel', 600, 570, '/imagenes/Conciertos/CuartetoDeNos-12Marzo.webp', 1, 0),
                                                                                                                                                            (6, 'Expo Arte Contemporáneo', 'Muestra internacional de pinturas y esculturas.', '2026-08-01', '10:00:00', 15.00, 'Museo de la Ciudad', 2000, 1990, '/imagenes/Conciertos/Paulo Londra-29Agosto.webp', 1, 0),
                                                                                                                                                            (7, 'Mistura & Sabor', 'Feria gastronómica con los mejores chefs.', '2026-08-15', '11:00:00', 30.00, 'Campo Ferial', 10000, 9850, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 0),
                                                                                                                                                            (7, 'Gala de Ballet El Lago de los Cisnes', 'Presentación estelar de la compañía nacional.', '2026-08-22', '20:00:00', 120.00, 'Gran Teatro Nacional', 1100, 1080, '/imagenes/Conciertos/CuartetoDeNos-12Marzo.webp', 1, 1),
                                                                                                                                                            (8, 'Circo de las Maravillas', 'Acrobacias extremas y magia sin animales.', '2026-07-30', '18:30:00', 55.00, 'Carpa Parque Norte', 2500, 2450, '/imagenes/Conciertos/Paulo Londra-29Agosto.webp', 1, 0),
                                                                                                                                                            (8, 'Fashion Week Primavera', 'Lanzamiento de las tendencias de la nueva temporada.', '2026-09-05', '19:00:00', 180.00, 'Hotel Marriott Salón A', 400, 395, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 0),
                                                                                                                                                            (8, 'Feria Internacional del Libro', 'Ingreso general y acceso a conferencias de autores.', '2026-07-28', '10:00:00', 10.00, 'Parque de los Próceres', 20000, 19900, '/imagenes/Conciertos/CuartetoDeNos-12Marzo.webp', 1, 1),
                                                                                                                                                            (8, 'Copa Gaming E-Sports', 'Final nacional de los videojuegos competitivos top.', '2026-09-20', '14:00:00', 70.00, 'Arena Universitaria', 3500, 3420, '/imagenes/Conciertos/Paulo Londra-29Agosto.webp', 1, 0),
                                                                                                                                                            (8, 'Tour Fantasmas del Centro', 'Recorrido peatonal nocturno lleno de mitos.', '2026-07-11', '21:00:00', 35.00, 'Punto de Encuentro Catacumbas', 50, 45, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 0),
                                                                                                                                                            (9, 'Yoga Masivo al Amanecer', 'Sesión de relajación frente al mar.', '2026-08-09', '06:30:00', 20.00, 'Malecón de la Costa', 800, 780, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 0),
                                                                                                                                                            (9, 'Neon Party Retro', 'Fiesta temática de los 80s y 90s con luces neón.', '2026-07-24', '23:00:00', 50.00, 'Club Discoteca Oxígeno', 600, 550, '/imagenes/Conciertos/CuartetoDeNos-12Marzo.webp', 1, 0),
                                                                                                                                                            (9, 'Canto por la Paz', 'Concierto coral filantrópico internacional.', '2026-08-30', '17:00:00', 40.00, 'Catedral Metropolitana', 1500, 1480, '/imagenes/Conciertos/Paulo Londra-29Agosto.webp', 1, 0),
                                                                                                                                                            (9, 'Taller de Cerámica Básica', 'Incluye materiales y horneado de tu pieza.', '2026-07-19', '15:00:00', 95.00, 'Casa Taller Barranco', 25, 20, '/imagenes/Conciertos/Airbag-23Mayo.webp', 1, 0); -- ◄ PUNTO Y COMA

-- 4. INSERT DE TICKETS (CORREGIDO: Solo usa id_usuario entre 1 y 4)
INSERT INTO ticket (id_usuario, id_evento, id_categoria, cantidad, subtotal, total, fecha_compra, estado, tipo_pago, detalle) VALUES
                                                                                                                                  (2, 1, 1, 2, 300.00, 300.00, '2026-06-01', 1, 'TARJETA_CREDITO', 'Zona VIP - Fila A'),
                                                                                                                                  (3, 2, 2, 1, 80.00, 80.00, '2026-06-02', 1, 'PAYPAL', 'Platea Central'),
                                                                                                                                  (4, 3, 3, 1, 45.00, 45.00, '2026-06-05', 1, 'YAPE', 'Kit de competidor incluido'),
                                                                                                                                  (1, 4, 3, 4, 100.00, 100.00, '2026-06-05', 1, 'TARJETA_DEBITO', 'Pack familiar de entradas'),
                                                                                                                                  (2, 5, 4, 2, 440.00, 440.00, '2026-06-10', 1, 'TARJETA_CREDITO', 'Early Bird general'),
                                                                                                                                  (3, 6, 4, 1, 350.00, 350.00, '2026-06-11', 1, 'TRANSFERENCIA', 'Pase corporativo VIP'),
                                                                                                                                  (4, 7, 4, 2, 120.00, 120.00, '2026-06-12', 1, 'EFECTIVO', 'Mesa compartida frente al escenario'),
                                                                                                                                  (1, 8, 5, 3, 120.00, 120.00, '2026-06-14', 1, 'TARJETA_DEBITO', 'Entradas niños y un adulto'),
                                                                                                                                  (2, 9, 6, 2, 30.00, 30.00, '2026-06-15', 1, 'YAPE', 'Acceso guiado de las 10am'),
                                                                                                                                  (3, 10, 7, 5, 150.00, 150.00, '2026-06-15', 1, 'PLIN', 'Tickets de acceso para grupo familiar'),
                                                                                                                                  (4, 11, 7, 2, 240.00, 240.00, '2026-06-16', 1, 'TARJETA_CREDITO', 'Mezzanine Preferencial'),
                                                                                                                                  (1, 12, 8, 2, 110.00, 110.00, '2026-06-17', 1, 'TARJETA_DEBITO', 'Butaca Lateral'),
                                                                                                                                  (2, 13, 8, 1, 180.00, 180.00, '2026-06-18', 1, 'PAYPAL', 'Acceso a pasarela y cocktail posterior'),
                                                                                                                                  (3, 14, 8, 3, 30.00, 30.00, '2026-06-19', 1, 'EFECTIVO', 'Tickets Abonos de 3 días Feria'),
                                                                                                                                  (4, 15, 8, 2, 140.00, 140.00, '2026-06-19', 1, 'TARJETA_CREDITO', 'Grada Norte Comunidad Gamer'),
                                                                                                                                  (2, 16, 8, 1, 35.00, 35.00, '2026-06-20', 1, 'YAPE', 'Tour de Misterio'),
                                                                                                                                  (3, 17, 9, 1, 20.00, 20.00, '2026-06-20', 1, 'PLIN', 'Incluye colchoneta de préstamo'),
                                                                                                                                  (4, 18, 9, 2, 100.00, 100.00, '2026-06-20', 1, 'TARJETA_DEBITO', 'Incluye un trago de cortesía'),
                                                                                                                                  (1, 19, 9, 2, 80.00, 80.00, '2026-06-20', 1, 'TRANSFERENCIA', 'Ubicación Nave Central'),
                                                                                                                                  (2, 20, 9, 1, 95.00, 95.00, '2026-06-20', 0, 'TARJETA_CREDITO', 'Ticket Cancelado por el usuario');